### ISSUE TITLE
How to handle in multiple pages condition?

### ISSUE THREAD

**Issue by jitendravyas** [cssanimation/gulp-sass-starter#4]
If we need to make more than one page with common header and footer

**Comment by donovanh** [comment]
Hi, my apologies for the late reply. I'd missed the notification :/

Currently this isn't really set up for multiple pages but you could use https://www.npmjs.com/package/gulp-file-include for such a task. Otherwise I'd recommend more dedicated tools such as either Metalsmith or Jekyll.
